/* Generated by cast/gen_wrapper */
static void *__handle;
struct wl_cursor_theme *wl_cursor_theme_load(const char *name, int size, struct wl_shm *shm)
{
	static struct wl_cursor_theme *(*__f)(const char *, int , struct wl_shm *);
	if (!__f)
		__f = dlsym(__handle, "wl_cursor_theme_load");

	return __f(name, size, shm);
}
struct wl_cursor *wl_cursor_theme_get_cursor(struct wl_cursor_theme *theme, const char *name)
{
	static struct wl_cursor *(*__f)(struct wl_cursor_theme *, const char *);
	if (!__f)
		__f = dlsym(__handle, "wl_cursor_theme_get_cursor");

	return __f(theme, name);
}
struct wl_buffer *wl_cursor_image_get_buffer(struct wl_cursor_image *image)
{
	static struct wl_buffer *(*__f)(struct wl_cursor_image *);
	if (!__f)
		__f = dlsym(__handle, "wl_cursor_image_get_buffer");

	return __f(image);
}
