/* Generated by cast/gen_wrapper */
static void *__handle;
struct wl_proxy *wl_proxy_marshal_flags(struct wl_proxy *proxy, uint32_t opcode, const struct wl_interface *interface, uint32_t version, uint32_t flags, ...)
{
	void *__args = __builtin_apply_args();
	static void *__f;
	if (!__f)
		__f = dlsym(__handle, "wl_proxy_marshal_flags");

	void *__res = __builtin_apply(__f, __args, 512);
	__builtin_return(__res);
}
void wl_proxy_destroy(struct wl_proxy *proxy)
{
	static void (*__f)(struct wl_proxy *);
	if (!__f)
		__f = dlsym(__handle, "wl_proxy_destroy");

	__f(proxy);
}
int wl_proxy_add_listener(struct wl_proxy *proxy, void (*(*implementation))(void), void *data)
{
	static int (*__f)(struct wl_proxy *, void (*(*))(void), void *);
	if (!__f)
		__f = dlsym(__handle, "wl_proxy_add_listener");

	return __f(proxy, implementation, data);
}
uint32_t wl_proxy_get_version(struct wl_proxy *proxy)
{
	static uint32_t (*__f)(struct wl_proxy *);
	if (!__f)
		__f = dlsym(__handle, "wl_proxy_get_version");

	return __f(proxy);
}
struct wl_display *wl_display_connect(const char *name)
{
	static struct wl_display *(*__f)(const char *);
	if (!__f)
		__f = dlsym(__handle, "wl_display_connect");

	return __f(name);
}
int wl_display_dispatch_pending(struct wl_display *display)
{
	static int (*__f)(struct wl_display *);
	if (!__f)
		__f = dlsym(__handle, "wl_display_dispatch_pending");

	return __f(display);
}
int wl_display_flush(struct wl_display *display)
{
	static int (*__f)(struct wl_display *);
	if (!__f)
		__f = dlsym(__handle, "wl_display_flush");

	return __f(display);
}
int wl_display_roundtrip(struct wl_display *display)
{
	static int (*__f)(struct wl_display *);
	if (!__f)
		__f = dlsym(__handle, "wl_display_roundtrip");

	return __f(display);
}
int wl_display_prepare_read(struct wl_display *display)
{
	static int (*__f)(struct wl_display *);
	if (!__f)
		__f = dlsym(__handle, "wl_display_prepare_read");

	return __f(display);
}
int wl_display_read_events(struct wl_display *display)
{
	static int (*__f)(struct wl_display *);
	if (!__f)
		__f = dlsym(__handle, "wl_display_read_events");

	return __f(display);
}
